<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE contact-details [
	<!ELEMENT foodko (homepage)>
	<!ELEMENT bestsellers (food)>
	<!ELEMENT shop (food)>

	<!ELEMENT advertisement (#PCDATA)>
	<!ELEMENT voucher (#PCDATA)>
	<!ELEMENT bestsellers (#PCDATA)>
	<!ELEMENT food (#PCDATA)>
	<!ELEMENT offer (#PCDATA)>
	<!ELEMENT contact (#PCDATA)>
	<!ELEMENT footer (#PCDATA)>
	<!ELEMENT information (#PCDATA)>
	<!ELEMENT inside (#PCDATA)>
	<!ELEMENT quicklink (#PCDATA)>
	<!ELEMENT seeinformation (#PCDATA)>
	<!ELEMENT others (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT content (#PCDATA)>
	<!ELEMENT shop (#PCDATA)>
	


	<!ATTLIST advertisement slide CDATA #REQUIRED>
	<!ATTLIST shop dropbar CDATA #REQUIRED>
	<!ATTLIST food id CDATA #REQUIRED>

]>

<foodko>
	<homepage> 
		<advertisement slide="2">Todays Menu</advertisement>
		<voucher>Promo</voucher>
		<bestsellers>
			<food>Sushi</food>
			<food>Adobo</food>
			<food>Halo-Halo</food>
			<food>Chinese Noodles</food>
		</bestsellers>
		<offer>Discount Membership</offer>
		<contact>Need Help</contact>
		<footer>
			<information>
				<inside>About me</inside>
				<inside>Contact us</inside>
			</information>
		<quicklink>
			<inside>About</inside>
			<inside>Blog</inside>
			<inside>Cart</inside>
			<inside>Contact</inside>
		</quicklink>
		<seeinformation>
		<inside>Santol, Boac, Marinduque
				Phone: 01254 698 785, 36598 254 987
				Email: foodko@gmail.com
		</inside>

		</seeinformation>
		</footer>

	</homepage>

	<shop dropbar="3"> 
		<food id="Chinesefood">
			<food>
				<name>Beijing Roasted Duck</name>
				<price>PHP240.00</price>
				<content>Peking duck is a dish from Beijing that has been prepared since the Imperial era. The meat is characterized by its thin, crispy skin, with authentic versions of the dish serving mostly the skin and little meat, sliced in front of the diners by the cook.
				</content>
		</food>
			<food>
				<name>HOT POT</name>
				<price>PHP150.00</price>
				<content>Hot pot, or hotpot (火锅 huǒguō), is one of the most popular dishes in China, especially in Sichuan Province or Chongqing. People cook in and eat from a simmering pot of soup stock (broth) on a gas/induction hob in the middle of the dining table with foodstuffs and condiments around the pot.
				</content>

		</food>
			<food>
				<name>MA PO TOFU</name>
				<price>PHP75.00</price>
				<content>Ma Po tofu (麻婆豆腐 Mápó dòufǔ ‘Pockmarked Granny beancurd’) is one of the most famous dishes in Chuan Cuisine (Sichuan food) with a history of more than 100 years. It consists of beancurd along with some minced meat (pork or beef) in a spicy sauce. The sauce is made from fermented black beans and chili paste (douban/douchi).
				</content>

		</food>
			<food>
				<name>CHINESE NOODLES</name>
				<price>PHP120.00</price>
				<content>Noodles are an essential ingredient and staple in Chinese cuisine. Chinese noodles vary widely according to the region of production, ingredients, shape or width, and manner of preparation. They are an important part of most regional cuisines within China, and other countries with sizable overseas Chinese populations.
				</content>

		</food>
			<food>
				<name>DIMSUM</name>
				<price>PHP45.00</price>
				<content>Dim sum is a large range of small Chinese dishes that are traditionally enjoyed in restaurants for brunch. Most modern dim sum dishes originated in China and are commonly associated with Cantonese cuisine, although dim sum dishes also exist in other Chinese cuisines.
				</content>

		</food>
		</food>
		<food id="Japanese Food">
			<food>
				<name>Sushi</name>
				<price>PHP145.00</price>
				<content>Sushi (すし, 寿司, 鮨, pronounced [sɯɕiꜜ] or [sɯꜜɕi]) is a traditional Japanese dish of prepared vinegared rice (鮨飯, sushi-meshi), usually with some sugar and salt, accompanying a variety of ingredients (ネタ, neta), such as seafood, often raw, and vegetables.
				</content>

			</food>
			<food>
				<name>UDON</name>
				<price>PHP110.00</price>
				<content>One of the three main noodle varieties eaten in Japan; udon noodles are thick, chewy, and traditionally made from wheat flour and brine water. Udon can be served in a number of different ways (mixed into stir fries, added to hot pots, served cold with a tsuyu or tentsuyu soup base on the side for dipping), but are most commonly used in noodle soups, where they are served in a savoury soup broth with different garnishes. Some of the most common udon noodle soup dishes include kitsune udon (‘fox udon’, topped with aburaage fried tofu), tempura udon (topped with tempura battered seafood and vegetables), and chikara udon (‘power udon’, topped with grilled mochi rice cakes).
				</content>

			</food>
			<food>
				<name>TEMPURA</name>
				<price>PHP75.00</price>
				<content>If you enjoy crispy fried foods, then you will love tempura. Tempura are pieces or slices of meat, fish, and/or vegetables that have been covered in a special tempura batter and deep fried until they become crunchy and pale gold in colour.
				</content>

			</food>
			<food>
				<name>YAKITORI</name>
				<price>PHP120.00</price>
				<content>With a name literally meaning ‘barbecued chicken’, yakitori are small skewers of bite-size chicken pieces seasoned with salt or brushed with a sauce, or tare, of mirin rice wine, soy sauce, sake alcohol, and sugar. There are many different types of yakitori, but the most common varieties are momo (chicken thigh), negima (chicken and spring onion), and tsukune (chicken meatballs).
				</content>

			</food>
			<food>
				<name>SASHIMI</name>
				<price>PHP45.00</price>
				<content>Possibly one of the most controversial dishes in all of Japanese cuisine, sashimi is raw fish or meat that has been expertly cut into thin slices and typically comes served with daikon radish, pickled ginger, wasabi and soy sauce. Sashimi differs from sushi in that all sushi is made with vinegared rice and does not always contain raw fish, while sashimi is almost exclusively raw fish and is never served with rice. The fish used to make sashimi must be as fresh as possible, both in order to minimise the risk of contamination, and because fresher fish makes for tastier sashimi.
				</content>

			</food>



		</food>
		<food>Filipino Food</food>
		<Others>
			<others>Cart Page</others>
			<others>Checkout Page</others>
			<others>Wishlist Page</others>
		</Others>
	</shop>
	


















</foodko>
	